apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: #TODO image指定
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: demo-server-service
  namespace: dev
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: demo-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: demo-server-service
                port:
                  number: 9090
