name: deploy eks demo

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
